--Create a noble win table if it doesn't exist
CREATE TABLE IF NOT EXISTS NOBLE_WIN (
    YEAR INT,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

--Insert sample data into the NOBLE_WIN table
INSERT INTO NOBLE_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
(1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
(1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
(1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
(1972, 'LITERATURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST'),
(1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
(1973, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER'),
(1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT'),
(1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST'),
(1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST');

--Select all records from the NOBLE_WIN table where the subject does not start with 'P'
SELECT*
FROM NOBLE_WIN
WHERE SUBJECT NOT LIKE 'P%';